MODE: dev
PORT: 8012
CLIENT_ORIGIN: http://localhost:3001
# === db ===
POSTGRES_HOST: localhost
POSTGRES_USER: xuyuanmao
POSTGRES_PASSWORD: chen4212
POSTGRES_DB: einstein
POSTGRES_PORT: 5432
# === bucket ===
MINIO_ACCESS_KEY: minioadmin
MINIO_SECRET_KEY: minioadmin
MINIO_BUCKET_URL: localhost:9000
MINIO_BUCKET: einstein-file
# === email ===
EMAIL_FROM: no-reply@arxtect.com
SMTP_HOST: email-smtp.ap-northeast-1.amazonaws.com
SMTP_PASS: BJt49FpFAnPY6gpd3eSuW2WXoGivI+z+yJZCoY9wmXzZ
SMTP_PORT: 465
SMTP_USER: AKIA47CRWTAI6LG7ZDKM

# === Legacy Env ===
REDIS_HOST: localhost:6379
REDIS_PWD: jhkdjhkjdhsIUTYURTU_76Dhb2
REDIS_DB: 15
DOMAIN: arxtect.com,editor.com,arxtect.com,www.arxtect.com,localhost,network.jancsitech.net,10.10.101.160,10.10.101.159

#EMAIL_FROM: no-reply@tzion.xyz
#SMTP_HOST: smtp.feishu.cn
#SMTP_PASS: jU4Mqn7vthUFnyt2
#SMTP_PORT: 465
#SMTP_USER: no-reply@tzion.xyz
#EMAIL_FROM: mail@pointer.ai
#SMTP_HOST: mail.pointer.ai
#SMTP_PASS: mail
#SMTP_PORT: 587
#SMTP_USER: mail

TOKEN_SECRET: my-ultra-secure-json-web-token-string
TOKEN_EXPIRED_IN: 160m
TOKEN_MAXAGE: 160

ACCESS_TOKEN_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCUEFJQkFBSkJBTzVIKytVM0xrWC91SlRvRHhWN01CUURXSTdGU0l0VXNjbGFFKzlaUUg5Q2VpOGIxcUVmCnJxR0hSVDVWUis4c3UxVWtCUVpZTER3MnN3RTVWbjg5c0ZVQ0F3RUFBUUpCQUw4ZjRBMUlDSWEvQ2ZmdWR3TGMKNzRCdCtwOXg0TEZaZXMwdHdtV3Vha3hub3NaV0w4eVpSTUJpRmI4a25VL0hwb3piTnNxMmN1ZU9wKzVWdGRXNApiTlVDSVFENm9JdWxqcHdrZTFGY1VPaldnaXRQSjNnbFBma3NHVFBhdFYwYnJJVVI5d0loQVBOanJ1enB4ckhsCkUxRmJxeGtUNFZ5bWhCOU1HazU0Wk1jWnVjSmZOcjBUQWlFQWhML3UxOVZPdlVBWVd6Wjc3Y3JxMTdWSFBTcXoKUlhsZjd2TnJpdEg1ZGdjQ0lRRHR5QmFPdUxuNDlIOFIvZ2ZEZ1V1cjg3YWl5UHZ1YStxeEpXMzQrb0tFNXdJZwpQbG1KYXZsbW9jUG4rTkVRdGhLcTZuZFVYRGpXTTlTbktQQTVlUDZSUEs0PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
ACCESS_TOKEN_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTzVIKytVM0xrWC91SlRvRHhWN01CUURXSTdGU0l0VQpzY2xhRSs5WlFIOUNlaThiMXFFZnJxR0hSVDVWUis4c3UxVWtCUVpZTER3MnN3RTVWbjg5c0ZVQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
ACCESS_TOKEN_EXPIRED_IN: 1500m
ACCESS_TOKEN_MAXAGE: 150

REFRESH_TOKEN_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT1FJQkFBSkJBSWFJcXZXeldCSndnYjR1SEhFQ01RdHFZMTI5b2F5RzVZMGlGcG51a0J1VHpRZVlQWkE4Cmx4OC9lTUh3Rys1MlJGR3VxMmE2N084d2s3TDR5dnY5dVY4Q0F3RUFBUUpBRUZ6aEJqOUk3LzAxR285N01CZUgKSlk5TUJLUEMzVHdQQVdwcSswL3p3UmE2ZkZtbXQ5NXNrN21qT3czRzNEZ3M5T2RTeWdsbTlVdndNWXh6SXFERAplUUloQVA5UStrMTBQbGxNd2ZJbDZtdjdTMFRYOGJDUlRaZVI1ZFZZb3FTeW40YmpBaUVBaHVUa2JtZ1NobFlZCnRyclNWZjN0QWZJcWNVUjZ3aDdMOXR5MVlvalZVRlVDSUhzOENlVHkwOWxrbkVTV0dvV09ZUEZVemhyc3Q2Z08KU3dKa2F2VFdKdndEQWlBdWhnVU8yeEFBaXZNdEdwUHVtb3hDam8zNjBMNXg4d012bWdGcEFYNW9uUUlnQzEvSwpNWG1heWtsaFRDeWtXRnpHMHBMWVdkNGRGdTI5M1M2ZUxJUlNIS009Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
REFRESH_TOKEN_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBSWFJcXZXeldCSndnYjR1SEhFQ01RdHFZMTI5b2F5Rwo1WTBpRnBudWtCdVR6UWVZUFpBOGx4OC9lTUh3Rys1MlJGR3VxMmE2N084d2s3TDR5dnY5dVY4Q0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
REFRESH_TOKEN_EXPIRED_IN: 1600m
REFRESH_TOKEN_MAXAGE: 160

API_KEY: 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
API_URL: ""
LISTEN: ""
PROXY: ""
ADMIN_EMAIL: ["tzion@open2any.tools", "admin@open2any.tools"]
ADMIN_PASSWORD: test12312312

## gitea
GITEA_HOST: http://3.227.9.181:3006
GITEA_ADMIN_USER: arxtect
GITEA_ADMIN_PASSWORD: arxtect@123
MEILI_HOST: http://10.10.101.199:7700
MEILI_KEY: HmPEKZhcoANzRt3DTPhRQVRxPEVZw7m2TymKwKhs_6xdnky

# dify
DIFY_CONSOLE_UMAIL: admin@arxtect.com
DIFY_CONSOLE_PASSWORD: admin123456
DIFY_HOST: http://network.jancsitech.net:1510
DIFY_KEY: 12312

# === y-redis ===

REDIS: redis://yredismq_container:6379



# use ip address
AUTH_PERM_CALLBACK: http://10.10.100.79:8012/api/v1/yredis/auth/perm # Change the ip address to a real IP address
YDOC_UPDATE_CALLBACK: http://10.10.100.79:8012/api/v1/yredis/ydoc # Change the ip address to a real IP address

# log everything
LOG: "*"

## Auth tokens
AUTH_PUBLIC_KEY: '{"key_ops":["verify"],"ext":true,"kty":"EC","x":"cmqZS41vyna6FUhVMz41NOFm5XfMc18CS5CId4Jb5pRNsjkVgiDn5LKBDszrj1C_","y":"UD8M0luXnv3N_TR-cdGn3TkccEFBAbju9J_vwweeQ2zZB7qvLac05pljZ2PA8qSs","crv":"P-384"}'
AUTH_PRIVATE_KEY: '{"key_ops":["sign"],"ext":true,"kty":"EC","x":"cmqZS41vyna6FUhVMz41NOFm5XfMc18CS5CId4Jb5pRNsjkVgiDn5LKBDszrj1C_","y":"UD8M0luXnv3N_TR-cdGn3TkccEFBAbju9J_vwweeQ2zZB7qvLac05pljZ2PA8qSs","crv":"P-384","d":"bU7sfhJbZjDienGxXp9Qc2YDwz_u6p3lsKWnpX1IDuliYcXGuC-pGKjcOztc6sW5"}'
YREDIS_ACCESS_TOKEN_EXPIRED_IN: 1500m
# ======